version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: sacc_postgres_prod
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-sacc_db}
            POSTGRES_USER: ${POSTGRES_USER:-sacc_user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sacc_password}
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backups:/backups
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sacc_user} -d ${POSTGRES_DB:-sacc_db}"]
            interval: 30s
            timeout: 10s
            retries: 5

    backend:
        build:
            context: ./backend
        env_file:
            - $SACC_CONFIG_PATH/.env
        tty: true
        depends_on:
            postgres:
                condition: service_healthy

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        env_file:
            - $SACC_CONFIG_PATH/.env
        tty: true

    nginx:
        build: ./nginx/
        restart: unless-stopped
        # ports:
        #     - 80:80
        #     - 443:443
        depends_on:
            - backend
            - frontend
        volumes:
            - /etc/ssl:/etc/ssl

volumes:
    postgres_data:
        driver: local
