

services:

    postgres:
        image: postgres:16
        container_name: sacc_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-sacc_db}
            POSTGRES_USER: ${POSTGRES_USER:-sacc_user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sacc_password}
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backups:/backups
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sacc_user} -d ${POSTGRES_DB:-sacc_db}"]
            interval: 10s
            timeout: 10s
            retries: 5

    backend:
        build:
            context: ./backend
        env_file:
            - ./.env
        volumes:
            - ./backend:/app
        tty: true
        depends_on:
            postgres:
                condition: service_healthy

    frontend:
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./frontend:/app
        tty: true

    nginx:
        build: ./nginx/
        restart: unless-stopped
        ports:
            - 80:80
            # - 443:443
        depends_on:
            - backend
            - frontend

volumes:
    postgres_data:
        driver: local
