version: '3.8'

services:
    backend:
        build:
            context: ./backend
        env_file:
            - $SACC_CONFIG_PATH/.env
        tty: true

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        env_file:
            - $SACC_CONFIG_PATH/.env
        tty: true

    nginx:
        build: ./nginx/
        restart: unless-stopped
        # ports:
        #     - 80:80
        #     - 443:443
        depends_on:
            - backend
            - frontend
        volumes:
            - /etc/ssl:/etc/ssl
